# Generated by Django 5.2.4 on 2025-07-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('remote', models.BooleanField(default=False)),
                ('url', models.URLField()),
                ('date_posted', models.DateTimeField()),
                ('keywords', models.TextField()),
                ('source', models.CharField(max_length=50)),
            ],
        ),
    ]
