# Generated by Django 5.2.4 on 2025-07-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='job',
            name='remote',
        ),
        migrations.RemoveField(
            model_name='job',
            name='source',
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
